version: '3.9'

services:
    php:
        build:
            context: ./php
            dockerfile: Dockerfile-81
        volumes:
            - ./../:/app
        tty: true

    ganache:
        build:
            context: ./ganache
            dockerfile: Dockerfile
        ports:
            - "8545"
